### ISSUE TITLE
[Request] Support for Reinforced Shulker Boxes

### ISSUE THREAD

**Issue by TprScruffy** [TheIllusiveC4/CuriousShulkerBoxes#21] opened 2022-08-23 10:41 UTC
These two mods are perfect for cross compatibility. Maybe something to add for the next version. Love not having to stuff around with backpack mods anymore.

https://www.curseforge.com/minecraft/mc-mods/reinforced-shulker-boxes

Thanks
Scruff

**Comment by TheIllusiveC4** [comment] 2024-10-08 06:54
Duplicate of https://github.com/illusivesoulworks/shulkerboxslot/issues/11

**Closed as not planned by TheIllusiveC4** 2024-10-08 06:54 UTC
Labels: status: duplicate, type: enhancement
