### ISSUE TITLE
[Request]: Reinforced Shulker Boxes support !

### ISSUE THREAD

**Issue by meowisme** [TheIllusiveC4/CuriousShulkerBoxes#28] opened 2023-08-09 06:39 UTC
### What is the new feature or improvement?

Seems there have been a few requests for this but none in the good year of 2023 !

Would be so lovely to be able to have [Reinforced Shulker Boxes](https://www.curseforge.com/minecraft/mc-mods/reinforced-shulker-boxes) supported with this :]
This Trinket mod is really nice but not being able to put on my Reinforced boxes is a bit sad, especially with how much looting I do, and I have a wearable backpack mod but it sucks not being able to wear a chestplate as well.

Thanks much ! :]
![image](https://github.com/illusivesoulworks/shulkerboxslot/assets/127144330/f44f1f10-4b0e-4cf4-8576-6543c1fc668f)

**Comment by TheIllusiveC4** [comment] 2024-10-08 06:55
Duplicate of https://github.com/illusivesoulworks/shulkerboxslot/issues/11

**Closed as not planned by TheIllusiveC4** 2024-10-08 06:55 UTC
Labels: status: duplicate, type: enhancement
