### ISSUE TITLE
[Request] Support for Reinforced Shulker Boxes

### ISSUE THREAD

**Issue by Tander** [TheIllusiveC4/CuriousShulkerBoxes#24] opened 2022-12-06 23:16 UTC
Would be nice to add support for modded shulkers. [Reinforced Shulker Boxes](https://www.curseforge.com/minecraft/mc-mods/reinforced-shulker-boxes) to be more precise, since is a successor of [Iron Shulker Boxes](https://www.curseforge.com/minecraft/mc-mods/iron-shulker-boxes) (which is still only for 1.16)

**Comment by DanMeadWasTaken** [comment] 2023-02-15 18:11
I second this, as it's also compatible with quick shulker and shulkerbox enchants- which is looking to add compatibility with shulkerbox slot when it updates to 1.19.3 (presumably 1.20 if it doesn't update to 1.19.3)

It'd honestly be like having mod that adds backpacks with upgrades, but still within the spectrum of vanilla.

**Comment by TheIllusiveC4** [comment] 2024-10-08 06:55
Duplicate of https://github.com/illusivesoulworks/shulkerboxslot/issues/11

**Closed as not planned by TheIllusiveC4** 2024-10-08 06:55 UTC
Labels: status: duplicate, type: enhancement
